### ISSUE TITLE
Nice to haves for revised vaults and strats

### ISSUE THREAD

**Issue by Tritium-VLK** [GalloDaSballo/badger-sett-1.5#1]
Not sure if this all fits into 1.5 but for a list.

- A way to freeze deposits and/or withdraws on the vault to better handle migrations
- Standard outputs from harvest that can be used to analyize/revert if too much slippage
- Full compostability (no blocklocks or EOA only)
- the ability to route fees somewhere other than governance (quite important)
- the ability to route performance fees and withdraw fees separately (less important)

**Comment by GalloDaSballo** [comment]
Achieved
